### ISSUE TITLE
pickles

### ISSUE THREAD

**Issue by liuhengli** [grigorisg9gr/deformable_tracking_review_ijcv2016#1]
I want to know where I can get these pickles files(modelln_opencv_sdm.pkl).  I only find the 300VW train dataset and not find the testdata can you give me a link?

**Comment by grigorisg9gr** [comment]
I am not sure what you mean with the 300vW train, the link should contain all the 114 clips. 
Also, please drop me a mail (or share yours) to send you the pkl files.

**Comment by liuhengli** [comment]
My mail is 501392366@qq.com. The train dataset I can download, but your README say using testset.

**Comment by grigorisg9gr** [comment]
How many clips does the dataset that you downloaded include?

**Comment by liuhengli** [comment]
the dataset total have 407 files, and each file have a annot and a vid.avi file. not frames file

**Comment by grigorisg9gr** [comment]
Sure, so you have to extract the frames from the videos. 

From what you are saying it seems that the testset is there. So, you can find more info about the dataset in any of our papers, but the 300vW includes 50 videos for training and 64 for testing.
